version: '3'

services:
  mongodb:
    image: mongo:5.0.6-focal
    hostname: "mongodb"
    container_name: company-registry_mongodb
    ports:
      - ${MONGODB_PORT}:27017
    restart: unless-stopped
