version: '3'

services:
  mongodb:
    image: mongo:4.2.3-bionic
    hostname: "mongodb"
    container_name: company-registry_mongodb
    ports:
      - ${MONGODB_PORT}:27017
    restart: unless-stopped
