# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
    - name: Install npm dependencies
      run: npm ci
    - name: Perform style check
      run: npm run lint
    - name: Perform test check
      run: npm test
      env:
        CI: true
    - name: Deploy to Heroku
      if: ${{ github.event_name == 'push' }}
      uses: AkhileshNS/heroku-deploy@v3.0.0
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
